{ lib, ... }:
{
  home.file = {
    ".config/kitty/kitty.conf" = lib.mkOverride 200 {
      text = ''
        font_family SauceCodePro Nerd Font
        font_size 12
        enable_audio_bell no
        symbol_map U+f6a9,U+f2db,U+f538 Font Awesome 6 Free Solid
        
        tab_bar_edge top
        tab_bar_style powerline
        tab_bar_min_tabs 1
        
        active_tab_foreground #ffffff
        active_tab_background #437019
        inactive_tab_foreground #ffffff
        inactive_tab_background #666666
        tab_bar_background #151515
        
        cursor_shape block
        cursor_blink_interval 0
        
        shell_integration no-cursor
        
        map ctrl+shift+d new_tab_with_cwd 

        include /home/ian/.config/kitty/themes/jellybeans.conf
      '';
    };

    ".config/kitty/themes/jellybeans.conf" = {
      text = ''
        background #111111
        foreground #dedede
        cursor #dedede
        selection_background #464d91
        color0 #919191
        color8 #bdbdbd
        color1 #e17373
        color9 #ffa0a0
        color2 #94b978
        color10 #bddeab
        color3 #ffb97b
        color11 #ffdba0
        color4 #96bddb
        color12 #b1d7f6
        color5 #e1c0fa
        color13 #fbdaff
        color6 #00988e
        color14 #19b2a7
        color7 #dedede
        color15 #ffffff
        selection_foreground #111111

        # START_AUTOGENERATED_TAB_STYLE
        # Feel free to update these colors manually and remove these comments.
        active_tab_foreground   #eeeeee
        active_tab_background   #464d91
        inactive_tab_foreground #9aa5ce
        inactive_tab_background #24283b
        # END_AUTOGENERATED_TAB_STYLE
      '';
    };
  };
}
